theme:  jekyll-theme-minimal
plugins:
- jekyll-remote-theme
title: Hyun Lab Homepage
description: Hyun Research Lab studies interesting nonlinear systems such as flapping wing vehicles, bicopters, quadrotors, and impulsive systems.

remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "Issues":
      - "https://github.com/Hyun-Research-Lab/Hyun-Research-Lab.github.io/issues"
    "Source on GitHub":
      - "https://github.com/Hyun-Research-Lab/Hyun-Research-Lab.github.io"
      
